### ISSUE TITLE
Quick Q: what's special about the *_default themes?

### ISSUE THREAD

**Issue by aryzing** [projekt0n/github-nvim-theme#158]
Sorry if this is an absurd question, but I just don't understand what's so "default" about the `*_default` themes. All other theme names make sense to me, but I don't see what's special about the *_default themes: what gives them their name?

**Comment by ful1e5** [comment]
**_default** themes are developed by primer(GitHub's design system) and without one are legacy themes. Currently, GitHub uses "*_default" themes as default on [github.com](https://github.com/settings/appearance) that's why they named them with "Default" postfix.

Check the [primer.style](https://primer.style/) and [github-vscode-theme#install](https://github.com/primer/github-vscode-theme#install) for more information.
