### ISSUE TITLE
Yaml keys are not being coloured

### ISSUE THREAD

**Issue by luisdavim** [projekt0n/github-nvim-theme#285]
Hi, I'm using the latest version of this theme and treesitter.
this is how this yaml file https://github.com/luisdavim/synthetic-checker/blob/main/checks.yaml looks like:

![image](https://github.com/projekt0n/github-nvim-theme/assets/173006/4fff4bf6-2fd7-4c57-9350-7ff2e523142c)

**Comment by luisdavim** [comment]
on JSON files the keys are coloured but they are red instead of green.
![image](https://github.com/projekt0n/github-nvim-theme/assets/173006/fec2a36a-b30a-420b-a5bd-df8262631b4a)

**Comment by tmillr** [comment]
hmmm strange. For the json, put the cursor over the red highlights and do `:Inspect`. What does it say? If I had to guess, it's probably red due to a syntax/parsing error (e.g. you're missing a comma somewhere, or there's an extra comma somewhere, etc.).

**Comment by luisdavim** [comment]
There's no syntax error, that files is from an upstream Kubernetes api definition, I'm using the high contrast variant, I'm not at my computer right now but I'll check the other variants later.

**Comment by tmillr** [comment]
You can try using the `:Inspect` cmd on the yaml keys as well to see what it says.

<img width="428" alt="Screenshot 2023-07-28 at 1 03 23 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/2a170dba-474a-4026-aac8-6029e880759e">

**Comment by luisdavim** [comment]
This is what I get in yaml:
![image](https://github.com/projekt0n/github-nvim-theme/assets/173006/3467297b-93c6-4089-9003-6cc1ea37e962)

An in json:
![image](https://github.com/projekt0n/github-nvim-theme/assets/173006/3452fdf9-7058-47ec-8096-b32188179eb2)

And here's a minimal valid json file:
![image](https://github.com/projekt0n/github-nvim-theme/assets/173006/abbb731e-0321-484d-bb69-110fa788369a)

I'm on the latest versions of all plugins and treesitter syntaxes.

This is the list of plugins I have, I don't think any of them overrides highlights but I may be wrong.

**Comment by tmillr** [comment]
Yeah it appears that treesitter highlighting is not getting used for some reason, and there could be multiple reasons for this which don't have anything to do with the theme. IIRC, a neovim release only comes bundled with with a few ts parsers (e.g. viml, lua, vimdoc, maybe c). Are you sure you have the parsers for the other languages installed? And do you have the [nvim-treesitter plugin](https://github.com/nvim-treesitter/nvim-treesitter) installed?

> sohuldn't this theme also work for popular file types without Treesitter?

This is a question best suited for the repo owner and sole maintainer, @ful1e5. When I first came across this plugin just a few months ago the syntax colors were off, even for treesitter. Since this was really the only plugin for the new gh theme (which is what I wanted), and pretty much the only Lua-based neovim plugin, and prob the most popular as well, I decided to contribute some fixes to the syntax highlights. I have only really focused on treesitter-based highlighting so far as this seems to be the default for nvim now, so fixing those should be prioritized first.

Maybe someone can submit a patch, or maybe I will if I find the time, but I would suggest getting your treesitter setup fixed. Ts highlighting is enabled on a per-buffer basis via an autocmd I believe, but you can also enable it manually with `:TSBufEnable highlight`.

Some other things you can try:

- To check if a parser is installed and can be found in rtp, do `:=vim.treesitter.language.add('json')`. This will error otherwise.
- Check your `nvim-treesitter` plugin config
- Run `:checkhealth nvim-treesitter` and/or `:checkhealth vim.treesitter`

**Comment by luisdavim** [comment]
Yeah, got my tree sitter working and I get the expected colours now.
