### ISSUE TITLE
How to get this to match the original theme?

### ISSUE THREAD

**Issue by veranorooz** [projekt0n/github-nvim-theme#288]
When viewed side-by-side, the same file looks different with this theme compared to GitHub or the VS Code theme (or Helix). Is there a way to fix this? I am not well versed on themes or colors so I cannot override myself.

**Comment by tmillr** [comment]
Are you using the latest version/release of this plugin? And are you using treesitter for highlighting (and have it setup properly)?

**Comment by nonzac** [comment]
I am on the latest release of the theme.  I use treesitter on stock settings. For comparison, below is how the same code looks like on GitHub vs Neovim on GitHub dark default.

### GitHub
![image](https://github.com/projekt0n/github-nvim-theme/assets/134659163/de606009-538b-4d7c-8e00-9179bec7fba6)

### Neovim
![image](https://github.com/projekt0n/github-nvim-theme/assets/134659163/956692c8-c1b4-4d5a-9064-b7b034250740)

**Comment by veranorooz** [comment]
Yes I am on the latest release and treesitter works (default configuration). Although I just did a more thorough comparison and Helix doesn't seem to match GitHub either.

I guess this is caused by the subtle differences in parsing?

**Comment by tmillr** [comment]
The syntax highlights should be quite close for most common langs. Getting them 100% accurate takes alot more work. Which lang are you having issues with? Can you post a screenshot?

**Comment by veranorooz** [comment]
hi, here's a comparison of a struct in rust between neovim using this theme (either dark default on v0.0.7 or dark high contrast on master, they look the same) vs. vscode using the original theme. (ignore the black background on neovim, it's tranparent).

neovim:

![image](https://github.com/projekt0n/github-nvim-theme/assets/60433637/77af8c5a-767a-4e03-b56a-a19a128fb6ca)

vscode:

![image](https://github.com/projekt0n/github-nvim-theme/assets/60433637/adebe800-e28c-4fd6-9f19-18bb403a2984)

**Comment by tmillr** [comment]
The neovim screenshot looks fine to me.

The goal of this theme should be to recreate Github's themes as closely and accurately as possible (while trying to make good decisions in edge-cases where Github's theme is lacking). The goal is not to follow the vscode version and inherit the inaccuracies of their own recreation. Please compare colors against GitHub's website directly.

According to your vscode screenshot, the vscode version has incorrect highlights for `:`, as well as struct fields and `{}` brackets.

**Comment by veranorooz** [comment]
Huh, you are right that its actually vscode that doesn't match with GH. That's surprising. Although I still think that vscode has a more natural look so I will look into configuring it myself. Thank you!

**Comment by tmillr** [comment]
The biggest difference on display here is essentially the color/highlights of (struct) fields. When it comes to the current "GitHub theme", fields/props are usually either unhighlighted, or highlighted with a blueish color (the exact color depends on the specific theme/variant), depending upon the language. Idk why a few langs don't have highlighted fields (maybe that's the actual intent of GitHub, or maybe it's simply an accident or due to shortcomings); but for rust, fields do get highlighted.

IMO, there's both pros and cons to having these sort of extra highlights. On one hand, it can make the distinction between syntax elements easier to discern, on the other, too many highlights (or different colors) can quickly become overwhelming or distracting. So it can be sort of a subjective question and catch 22 for what's best.
