### ISSUE TITLE
Any colorscheme that looks like github code viewer?

### ISSUE THREAD

**Issue by NikoKS** [projekt0n/github-nvim-theme#298]
Hello, Thank you very much for this theme!

I was wondering if there is a colorscheme that match Github's native dark default code viewer? Here is a sample screenshot what it looks like:

<img width="1470" alt="Screenshot 2023-09-20 at 11 24 52" src="https://github.com/projekt0n/github-nvim-theme/assets/24285511/141ee42a-a068-45a7-bb4c-3ffc05e1ae3d">

I found that github_dark_dimmed is too light, and github_dark_high_contrast is too dark. Github's native dark default sits just right in the middle.

**Comment by tmillr** [comment]
hmmmm this is interesting. It may be because the bg is currently being derived (in a sort of manual fashion?) from the scale colors.

https://github.com/projekt0n/github-nvim-theme/blob/bf4cd7e05ff1ac9a301edcd5051b9cd7f5c81f0d/lua/github-theme/palette/github_dark.lua#L46

**Comment by NikoKS** [comment]
Thank you for the quick response @tmillr! looking forward the PR being merged.

**Comment by ful1e5** [comment]
Thanks, @tmillr for the PR! I appreciate your work on this issue.

The patched theme's canvas color is noticeably darker, almost like the `github_dark_default`. I'm not sure if this is a bug in the [primer/primitives](https://github.com/primer/primitives) or if we're missing something.

![Upstream](https://github.com/projekt0n/github-nvim-theme/assets/24286590/bef058c5-7648-43fa-9f67-5643618af543)

![Patch](https://github.com/projekt0n/github-nvim-theme/assets/24286590/fc75d99e-ab54-4d01-953c-ebb2e27128eb)

**Comment by tmillr** [comment]
> The patched theme's canvas color is noticeably darker, almost like the `github_dark_default`. I'm not sure if this is a bug in the [primer/primitives](https://github.com/primer/primitives) or if we're missing something.

hmmm do you mean in comparison to GitHub.com (the center window), or to what it was before the patch?

As for the former, on the bottom img, the bg of the left and center window match.

If you mean the latter (which I think is probably what you meant?), well for me here on the website while using the regular dark "theme" (i.e. ***Dark default***) that is indeed the correct bg of the code viewer it seems:

<img width="942" alt="Screenshot 2023-09-23 at 1 17 42 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/d204d540-28f5-48b8-9a10-10adbe65a83e">

It is close to the same color used for dark high contrast, but it is not the same color, it is just a touch lighter.

So it looks correct to me (based off this) if the goal is to match the colors of GitHub.com precisely. It just seems like GitHub chose 2 very similar bg colors for regular dark and dark high contrast.

---

On a somewhat unrelated note, it looks like `github_dark_default` in the plugin is the deprecated one yeah? I often get confused and forget whether it's `github_dark` or `github_dark_default` that is the deprecated one, so perhaps the deprecated one should be planned for removal? I also don't receive the deprecation message for some reason when I set the colorscheme to it, so maybe that's something we should look into as well?

**Comment by tmillr** [comment]
For reference, here's dark high contrast on the website:

<img width="924" alt="Screenshot 2023-09-23 at 1 48 07 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/d927cede-f106-40fb-b78b-ff2ff93de48f">

---

It's very similar to the bg of regular dark, but it's just a pinch darker.

**Comment by borisrorsvort** [comment]
The white theme is still different from the codeviewer white theme too

**Comment by ful1e5** [comment]
> On a somewhat unrelated note, it looks like `github_dark_default` in the plugin is the deprecated one yeah? I often get confused and forget whether it's `github_dark` or `github_dark_default` that is the deprecated one, so perhaps the deprecated one should be planned for removal? I also don't receive the deprecation message for some reason when I set the colorscheme to it, so maybe that's something we should look into as well?

@tmillr It looks like deprecating `github_dark_default` and `github_light_default` was an uninformed decision, because after a bit of research, I found that `Github Dark` and `Github Light` colors provided from Primer are actually for `Github Dark Default` and `Github Light Default` palettes. And `Github Dark` and `Github Light` colors in VSCode are legacy colors. So we have to restore this colorscheme. I'll push that restoration once #299 is merged.

**Comment by NikoKS** [comment]
Just wondering, is there any blocker to #299?

**Comment by tmillr** [comment]
Sorry I can't merge it, but it should be good to go

**Comment by tmillr** [comment]
> @tmillr It looks like deprecating `github_dark_default` and `github_light_default` was an uninformed decision, because after a bit of research, I found that `Github Dark` and `Github Light` colors provided from Primer are actually for `Github Dark Default` and `Github Light Default` palettes. And `Github Dark` and `Github Light` colors in VSCode are legacy colors. So we have to restore this colorscheme. I'll push that restoration once #299 is merged.

Yeah it's hard not to mix it up.

In the web ui they call it `Github Dark Default` and `Github Light Default`, but among the primitives files none of them are named `*default*`, so I'm sure that the `dark.*` file is for `Github Dark Default`, and the `light.*` file for `Github Light Default`.

i.e.

- https://github.com/projekt0n/github-nvim-theme/blob/48f95f763e1a98e508260a20e448c3ff2d91213a/lua/github-theme/palette/primitives/dark.lua
- https://github.com/projekt0n/github-nvim-theme/blob/48f95f763e1a98e508260a20e448c3ff2d91213a/lua/github-theme/palette/primitives/light.lua

I believe this is what you're saying as well but just making sure.

---

I suppose you could either leave it as it is now and remove the `*_default` versions, or change it so that `:colorscheme github_dark_default` would be the new way to set and refer to the regular dark theme (the plus being that the name matches up more closely). If the more manual parts of the palettes for these 2 themes were based off the wrong/old themes then I suppose that'd need to be fixed as well. I'd recommend just pulling directly from the primitives as much as possible.

**Comment by NikoKS** [comment]
@ful1e5, the color is back again after the latest commits

**Comment by ful1e5** [comment]
@NikoKS, consider switching your color scheme to `github_dark_default` to experience the dark color scheme similar to the one on the GitHub Web App. 

The `github_dark` color scheme is now considered a legacy package. For a clearer understanding, please refer to `:h github-nvim-theme-overview` or visit [README.md#supported-colorschemes](https://github.com/projekt0n/github-nvim-theme#supported-colorschemes--comparisons).
