### ISSUE TITLE
How to change `CocInlayHint` colors?

### ISSUE THREAD

**Issue by jonashaag** [projekt0n/github-nvim-theme#305]
Please excuse my naive question. I couldn't for the life of me figure out the right syntax to change the `CocInlayHint` colors. Here's what I have now, which has no effect:

```lua
return {
	{
		"projekt0n/github-nvim-theme",
		lazy = false, -- make sure we load this during startup if it is your main colorscheme
		priority = 1000, -- make sure to load this before all the other start plugins
		config = function()
			require("github-theme").setup({
				groups = {
					all = {
						CocInlayHint = { fg = '#ff0000', bg = '#0000ff' },
					}
				}
			})

			vim.cmd("colorscheme github_light_high_contrast")
		end,
	},
}
```

**Comment by tmillr** [comment]
Hi. This was probably due to a bug, but it should be working correctly now:

<img width="1440" alt="Screenshot 2024-07-09 at 9 59 53 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/601edf41-480d-4db1-b100-c317116356e6">

Please update your plugin to the latest release/tag (or HEAD, whichever you are using) and restart nvim. Feel free to re-open this issue, or open a new issue, if you are still having problems after that. You may also leave additional comments here.

**Comment by jonashaag** [comment]
It works, thanks!
